-- Estrutura para PythonAnywhere
-- Execute este arquivo primeiro para criar as tabelas

CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `senha` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ativo` enum('sim','nao') COLLATE utf8mb4_unicode_ci DEFAULT 'sim',
  `ultimo_acesso` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cursos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tipo_acao` enum('Curso','Oficina','Palestra','Workshop','Evento') COLLATE utf8mb4_unicode_ci NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `titulo_original` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descricao` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `descricao_original` text COLLATE utf8mb4_unicode_ci,
  `capa_curso` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `inicio_inscricoes` datetime NOT NULL,
  `fim_inscricoes` datetime NOT NULL,
  `orgao` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tema` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `carga_horaria` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `modalidade` enum('Presencial','Online','Híbrido') COLLATE utf8mb4_unicode_ci NOT NULL,
  `acessibilidade` enum('acessivel','exclusivo','nao_acessivel') COLLATE utf8mb4_unicode_ci NOT NULL,
  `recursos_acessibilidade` text COLLATE utf8mb4_unicode_ci,
  `publico_alvo` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `curso_gratuito` enum('sim','nao') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sim',
  `valor_curso_inteira` decimal(10,2) DEFAULT NULL,
  `valor_curso_meia` decimal(10,2) DEFAULT NULL,
  `requisitos_meia` text COLLATE utf8mb4_unicode_ci,
  `oferece_certificado` enum('sim','nao') COLLATE utf8mb4_unicode_ci NOT NULL,
  `pre_requisitos` text COLLATE utf8mb4_unicode_ci,
  `oferece_bolsa` enum('sim','nao') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'nao',
  `valor_bolsa` decimal(10,2) DEFAULT NULL,
  `requisitos_bolsa` text COLLATE utf8mb4_unicode_ci,
  `info_complementares` text COLLATE utf8mb4_unicode_ci,
  `info_adicionais` text COLLATE utf8mb4_unicode_ci,
  `parceiro_externo` enum('sim','nao') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'nao',
  `parceiro_nome` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parceiro_link` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parceiro_logo` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('ativo','inativo','rascunho') COLLATE utf8mb4_unicode_ci DEFAULT 'ativo',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_modalidade` (`modalidade`),
  KEY `idx_tema` (`tema`),
  KEY `idx_orgao` (`orgao`),
  KEY `idx_status` (`status`),
  KEY `idx_inscricoes` (`inicio_inscricoes`,`fim_inscricoes`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `turmas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `curso_id` int NOT NULL,
  `numero_turma` int NOT NULL DEFAULT '1',
  `nome_turma` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `endereco_unidade` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bairro_unidade` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `complemento` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vagas_totais` int NOT NULL,
  `vagas_ocupadas` int DEFAULT '0',
  `vagas_disponiveis` int GENERATED ALWAYS AS ((`vagas_totais` - `vagas_ocupadas`)) STORED,
  `inicio_aulas` date NOT NULL,
  `fim_aulas` date NOT NULL,
  `horario_inicio` time NOT NULL,
  `horario_fim` time NOT NULL,
  `status` enum('ativa','inativa','cancelada','concluida') COLLATE utf8mb4_unicode_ci DEFAULT 'ativa',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_curso_turma` (`curso_id`,`numero_turma`),
  KEY `idx_status` (`status`),
  KEY `idx_vagas` (`vagas_disponiveis`),
  CONSTRAINT `turmas_ibfk_1` FOREIGN KEY (`curso_id`) REFERENCES `cursos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `turmas_dias_semana` (
  `id` int NOT NULL AUTO_INCREMENT,
  `turma_id` int NOT NULL,
  `dia_semana` enum('Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_turma_dia` (`turma_id`,`dia_semana`),
  KEY `idx_turma` (`turma_id`),
  CONSTRAINT `turmas_dias_semana_ibfk_1` FOREIGN KEY (`turma_id`) REFERENCES `turmas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `plataformas_online` (
  `id` int NOT NULL AUTO_INCREMENT,
  `curso_id` int NOT NULL,
  `plataforma_digital` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `link_acesso` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vagas_totais` int NOT NULL,
  `vagas_ocupadas` int DEFAULT '0',
  `vagas_disponiveis` int GENERATED ALWAYS AS ((`vagas_totais` - `vagas_ocupadas`)) STORED,
  `aulas_assincronas` enum('sim','nao') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sim',
  `inicio_aulas` date DEFAULT NULL,
  `fim_aulas` date DEFAULT NULL,
  `horario_inicio` time DEFAULT NULL,
  `horario_fim` time DEFAULT NULL,
  `status` enum('ativa','inativa') COLLATE utf8mb4_unicode_ci DEFAULT 'ativa',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_curso` (`curso_id`),
  KEY `idx_vagas` (`vagas_disponiveis`),
  CONSTRAINT `plataformas_online_ibfk_1` FOREIGN KEY (`curso_id`) REFERENCES `cursos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;