version: "3.8"

services:
  mariadb:
    image: mariadb:11.6
    container_name: oportunidades_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carioca2025
      MYSQL_DATABASE: cursoscarioca
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - ./data_webciclo:/var/lib/mysql
      - ./init_webciclo:/docker-entrypoint-initdb.d
    networks:
      - mariadb_webciclo_network

networks:
  mariadb_webciclo_network:
    driver: bridge
