"""Initial_migration

Revision ID: 8848a6de01ce
Revises: 
Create Date: 2026-02-02 08:55:30.380933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8848a6de01ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_acao', sa.Enum('Curso', 'Oficina', 'Palestra', 'Workshop', 'Evento'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('titulo_original', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('descricao_original', sa.Text(), nullable=True),
    sa.Column('capa_curso', sa.String(length=500), nullable=True),
    sa.Column('inicio_inscricoes', sa.DateTime(), nullable=False),
    sa.Column('fim_inscricoes', sa.DateTime(), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=False),
    sa.Column('tema', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria', sa.String(length=100), nullable=False),
    sa.Column('modalidade', sa.Enum('Presencial', 'Online', 'Híbrido'), nullable=False),
    sa.Column('acessibilidade', sa.Enum('acessivel', 'exclusivo', 'nao_acessivel'), nullable=False),
    sa.Column('recursos_acessibilidade', sa.Text(), nullable=True),
    sa.Column('publico_alvo', sa.Text(), nullable=False),
    sa.Column('curso_gratuito', sa.Enum('sim', 'nao'), nullable=False),
    sa.Column('valor_curso_inteira', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_curso_meia', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('requisitos_meia', sa.Text(), nullable=True),
    sa.Column('oferece_certificado', sa.Enum('sim', 'nao'), nullable=False),
    sa.Column('pre_requisitos', sa.Text(), nullable=True),
    sa.Column('oferece_bolsa', sa.Enum('sim', 'nao'), nullable=False),
    sa.Column('valor_bolsa', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('requisitos_bolsa', sa.Text(), nullable=True),
    sa.Column('info_complementares', sa.Text(), nullable=True),
    sa.Column('info_adicionais', sa.Text(), nullable=True),
    sa.Column('parceiro_externo', sa.Enum('sim', 'nao'), nullable=False),
    sa.Column('parceiro_nome', sa.String(length=255), nullable=True),
    sa.Column('parceiro_link', sa.String(length=500), nullable=True),
    sa.Column('parceiro_logo', sa.String(length=500), nullable=True),
    sa.Column('csv_file', sa.String(length=500), nullable=True),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'rascunho'), nullable=True),
    sa.Column('is_inserted', sa.Enum('sim', 'nao'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Enum('sim', 'nao'), nullable=True),
    sa.Column('ultimo_acesso', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plataformas_online',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('plataforma_digital', sa.String(length=255), nullable=False),
    sa.Column('link_acesso', sa.String(length=500), nullable=True),
    sa.Column('vagas_totais', sa.Integer(), nullable=False),
    sa.Column('vagas_ocupadas', sa.Integer(), nullable=True),
    sa.Column('aulas_assincronas', sa.Enum('sim', 'nao'), nullable=False),
    sa.Column('inicio_aulas', sa.Date(), nullable=True),
    sa.Column('fim_aulas', sa.Date(), nullable=True),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'inativa'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('numero_turma', sa.Integer(), nullable=False),
    sa.Column('nome_turma', sa.String(length=100), nullable=True),
    sa.Column('endereco_unidade', sa.String(length=500), nullable=True),
    sa.Column('bairro_unidade', sa.String(length=100), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('vagas_totais', sa.Integer(), nullable=False),
    sa.Column('vagas_ocupadas', sa.Integer(), nullable=True),
    sa.Column('inicio_aulas', sa.Date(), nullable=False),
    sa.Column('fim_aulas', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'inativa', 'cancelada', 'concluida'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas_dias_semana',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo'), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas_dias_semana')
    op.drop_table('turmas')
    op.drop_table('plataformas_online')
    op.drop_table('users')
    op.drop_table('cursos')
    # ### end Alembic commands ###
